version: "2"
services:
  baikal:
    image: ckulka/baikal:nginx
    restart: unless-stopped
    ports:
      - "8087:80"
    volumes:
      - /opt/compose-data/baikal/config:/var/www/baikal/config
      - /opt/compose-data/baikal/data:/var/www/baikal/Specific
