apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      volumes:
      - name: {{ .Release.Name }}-vol
        hostPath:
          path: {{ .Values.volumes.hostPath }}
      containers:
      - image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
        name: freshrss-container
        ports:
        - name: http
          containerPort: {{ .Values.application.port }}
        env:
        - name: TZ
          value: {{ .Values.timezone }}
        volumeMounts:
        - name: freshrss-vol
          mountPath: {{ .Values.volumes.mountPath }}
