apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Name }}
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: {{ .Values.routing.matchRule }}
    services:
    - kind: Service
      name: {{ .Release.Name }}
      namespace: {{ .Release.Name }}
      port: {{ .Values.application.port }}