networks:
  traefik_traefik:
    external: true

services:
  pydio-cells:
    image: lscr.io/linuxserver/pydio-cells:latest
    container_name: pydio-cells
    hostname: pydio-cells
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/Rome
      - EXTERNALURL=pydio.pusi77.eu.org
    volumes:
      - /opt/compose-data/pydio/config:/config
    ports:
      - 8087:8080
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.freshrss.rule=Host(`pydio.pusi77.eu.org`)"
      - "traefik.http.routers.freshrss.entrypoints=websecure"
      - "traefik.http.routers.freshrss.tls=true"
      - "traefik.docker.network=traefik_traefik"