networks:
  traefik_traefik:
    external: true

services:
  pydio-cells:
    image: lscr.io/linuxserver/pydio-cells:latest
    container_name: pydio-cells
    hostname: pydio-cells
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/Rome
      - EXTERNALURL=pydio.pusi77.eu.org
    volumes:
      - /opt/compose-data/pydio/config:/config
    ports:
      - 8087:8080
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pydio.rule=Host(`pydio.pusi77.eu.org`)"
      - "traefik.http.routers.pydio.entrypoints=websecure"
      - "traefik.http.routers.pydio.tls=true"
      - "traefik.docker.network=traefik_traefik"

  mariadb:
    image: lscr.io/linuxserver/mariadb:latest
    container_name: mariadb
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/Rome
      # - MYSQL_ROOT_PASSWORD=portainer env var 
      - MYSQL_DATABASE=cells
    volumes:
      - /opt/compose-data/pydio/mariadb/config:/config
    ports:
      - 3306:3306
    restart: unless-stopped