version: '3'

networks:
  traefik:
    driver: bridge

services:
  traefik:
    image: traefik:latest
    container_name: traefik
    command:
      - --api.insecure=true
      - --providers.docker
      - --providers.docker.exposedbydefault=false
      - --providers.file.directory=/etc/traefik/dynamic
      #- --entryPoints.web.address=:80
      - --entryPoints.websecure.address=:443
    ports:
      #- "80:80"
      - "443:443"
      - "8081:8080"
    networks:
      - traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config/config.yml:/etc/traefik/dynamic/conf.yml:ro
      - /home/pusi77/certificates/:/certs/
    restart: unless-stopped
